checks:
    php:
        code_rating: true
        duplication: true

build:
    tests:
        override:
            -
                command: './bin/phpspec run -fpretty && ./bin/phpunit'
    environment:
        php:
            version: '7.1'

filter:
    paths: ["src"]
    excluded_paths:
        - "spec/"
        - "tests/"

tools:
    external_code_coverage:
        timeout: 1800
        runs: 2
